In [2]:
import pandas as pd
df = pd.read_csv("Table data.csv")
df

,Content,Video title,Video publish time,Views,Watch time (hours),Subscribers
0,Total,NaN,NaN,191389,566.8788,496
1,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,"Sep 27, 2022",28631,85.4885,62
2,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,"Aug 17, 2022",18977,44.9220,38
3,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...","Sep 23, 2022",9701,26.7575,29
4,veIUCvSYkos,Put an Ice cube on your pet to see their React...,"Sep 3, 2022",5259,20.9450,8
...,...,...,...,...,...,...
134,zpwE9w7zPfo,Cat of Egypt: Cat playing Hide & Seek | #catof...,"Aug 16, 2022",28,0.0564,0
135,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,"Oct 30, 2022",19,0.0525,0
136,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,"Oct 10, 2022",21,0.0482,0
137,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,"Oct 2, 2022",16,0.0302,0
138,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...","Nov 9, 2022",11,0.0294,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Content             139 non-null    object
 1   Video title         138 non-null    object
 2   Video publish time  138 non-null    object
 3   Views               139 non-null    int64
 4   Watch time (hours)  139 non-null    float64
 5   Subscribers         139 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 6.6+ KB

In [4]:
df.describe()

               Views  Watch time (hours)  Subscribers
count     139.000000          139.000000   139.000000
mean     2750.798561            8.146582     7.892086
std     16403.236332           48.517659    42.404828
min        11.000000            0.029400     0.000000
25%       193.000000            0.671300     0.000000
50%       704.000000            2.183800     2.000000
75%      1565.500000            4.939300     5.000000
max    191389.000000          566.878800   496.000000

In [5]:
df = df[df["Content"] != "Total"].copy()

In [6]:
df.isnull().sum()

Content               0
Video title           0
Video publish time    0
Views                 0
Watch time (hours)    0
Subscribers           0
dtype: int64

In [7]:
df = df.dropna(subset = ["Video title", "Video publish time"])

In [8]:
df

,Content,Video title,Video publish time,Views,Watch time (hours),Subscribers
1,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,"Sep 27, 2022",28631,85.4885,62
2,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,"Aug 17, 2022",18977,44.9220,38
3,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...","Sep 23, 2022",9701,26.7575,29
4,veIUCvSYkos,Put an Ice cube on your pet to see their React...,"Sep 3, 2022",5259,20.9450,8
5,Nngda4gKb18,Cat of Egypt remixes Usher's beat | #catofegyp...,"Sep 15, 2022",4506,15.3169,32
...,...,...,...,...,...,...
134,zpwE9w7zPfo,Cat of Egypt: Cat playing Hide & Seek | #catof...,"Aug 16, 2022",28,0.0564,0
135,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,"Oct 30, 2022",19,0.0525,0
136,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,"Oct 10, 2022",21,0.0482,0
137,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,"Oct 2, 2022",16,0.0302,0
138,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...","Nov 9, 2022",11,0.0294,0

In [9]:
df["Video publish time"] = pd.to_datetime(df["Video publish time"], errors = 'coerce')

In [10]:
df

,Content,Video title,Video publish time,Views,Watch time (hours),Subscribers
1,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62
2,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38
3,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29
4,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8
5,Nngda4gKb18,Cat of Egypt remixes Usher's beat | #catofegyp...,2022-09-15,4506,15.3169,32
...,...,...,...,...,...,...
134,zpwE9w7zPfo,Cat of Egypt: Cat playing Hide & Seek | #catof...,2022-08-16,28,0.0564,0
135,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0
136,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0
137,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0
138,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0

In [11]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("(", "").str.replace(")", "")

In [12]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers
1,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62
2,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38
3,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29
4,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8
5,Nngda4gKb18,Cat of Egypt remixes Usher's beat | #catofegyp...,2022-09-15,4506,15.3169,32
...,...,...,...,...,...,...
134,zpwE9w7zPfo,Cat of Egypt: Cat playing Hide & Seek | #catof...,2022-08-16,28,0.0564,0
135,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0
136,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0
137,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0
138,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0

In [13]:
df = df.drop_duplicates()

In [14]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers
1,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62
2,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38
3,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29
4,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8
5,Nngda4gKb18,Cat of Egypt remixes Usher's beat | #catofegyp...,2022-09-15,4506,15.3169,32
...,...,...,...,...,...,...
134,zpwE9w7zPfo,Cat of Egypt: Cat playing Hide & Seek | #catof...,2022-08-16,28,0.0564,0
135,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0
136,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0
137,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0
138,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0

In [15]:
df.dtypes

content                       object
video_title                   object
video_publish_time    datetime64[ns]
views                          int64
watch_time_hours             float64
subscribers                    int64
dtype: object

In [16]:
df = df.sort_values(by = "views", ascending = False)

In [17]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers
1,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62
2,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38
3,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29
4,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8
6,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17
...,...,...,...,...,...,...
136,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0
135,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0
131,YTnw6IWIlQM,Vibe With Cat of Egypt🐱🥰| #shorts #catofegypt ...,2022-11-11,16,0.0954,0
137,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0
138,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0

In [18]:
df = df.reset_index(drop = True)

In [19]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers
0,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62
1,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38
2,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29
3,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8
4,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17
...,...,...,...,...,...,...
133,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0
134,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0
135,YTnw6IWIlQM,Vibe With Cat of Egypt🐱🥰| #shorts #catofegypt ...,2022-11-11,16,0.0954,0
136,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0
137,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   content             138 non-null    object
 1   video_title         138 non-null    object
 2   video_publish_time  138 non-null    datetime64[ns]
 3   views               138 non-null    int64
 4   watch_time_hours    138 non-null    float64
 5   subscribers         138 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 6.6+ KB

In [21]:
df.head()

,content,video_title,video_publish_time,views,watch_time_hours,subscribers
0,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62
1,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38
2,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29
3,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8
4,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17

In [22]:
df["year"] = df["video_publish_time"].dt.year

In [23]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers,year
0,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62,2022
1,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38,2022
2,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29,2022
3,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8,2022
4,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17,2022
...,...,...,...,...,...,...,...
133,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0,2022
134,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0,2022
135,YTnw6IWIlQM,Vibe With Cat of Egypt🐱🥰| #shorts #catofegypt ...,2022-11-11,16,0.0954,0,2022
136,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0,2022
137,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0,2022

In [24]:
df["month"] = df["video_publish_time"].dt.month

In [25]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers,year,month
0,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62,2022,9
1,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38,2022,8
2,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29,2022,9
3,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8,2022,9
4,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17,2022,8
...,...,...,...,...,...,...,...,...
133,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0,2022,10
134,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0,2022,10
135,YTnw6IWIlQM,Vibe With Cat of Egypt🐱🥰| #shorts #catofegypt ...,2022-11-11,16,0.0954,0,2022,11
136,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0,2022,10
137,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0,2022,11

In [26]:
df["day_name"] = df["video_publish_time"].dt.day_name()
# which day video perfom best

In [27]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers,year,month,day_name
0,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62,2022,9,Tuesday
1,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38,2022,8,Wednesday
2,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29,2022,9,Friday
3,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8,2022,9,Saturday
4,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17,2022,8,Friday
...,...,...,...,...,...,...,...,...,...
133,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0,2022,10,Monday
134,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0,2022,10,Sunday
135,YTnw6IWIlQM,Vibe With Cat of Egypt🐱🥰| #shorts #catofegypt ...,2022-11-11,16,0.0954,0,2022,11,Friday
136,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0,2022,10,Sunday
137,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0,2022,11,Wednesday

In [28]:
df["views_per_subscribers"] = df["views"] / df["subscribers"]

In [29]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers,year,month,day_name,views_per_subscribers
0,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62,2022,9,Tuesday,461.790323
1,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38,2022,8,Wednesday,499.394737
2,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29,2022,9,Friday,334.517241
3,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8,2022,9,Saturday,657.375000
4,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17,2022,8,Friday,288.941176
...,...,...,...,...,...,...,...,...,...,...
133,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0,2022,10,Monday,inf
134,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0,2022,10,Sunday,inf
135,YTnw6IWIlQM,Vibe With Cat of Egypt🐱🥰| #shorts #catofegypt ...,2022-11-11,16,0.0954,0,2022,11,Friday,inf
136,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0,2022,10,Sunday,inf
137,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0,2022,11,Wednesday,inf

In [30]:
df["engagement"] = df["watch_time_hours"] / df["views"]

In [31]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers,year,month,day_name,views_per_subscribers,engagement
0,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62,2022,9,Tuesday,461.790323,0.002986
1,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38,2022,8,Wednesday,499.394737,0.002367
2,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29,2022,9,Friday,334.517241,0.002758
3,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8,2022,9,Saturday,657.375000,0.003983
4,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17,2022,8,Friday,288.941176,0.002836
...,...,...,...,...,...,...,...,...,...,...,...
133,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0,2022,10,Monday,inf,0.002295
134,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0,2022,10,Sunday,inf,0.002763
135,YTnw6IWIlQM,Vibe With Cat of Egypt🐱🥰| #shorts #catofegypt ...,2022-11-11,16,0.0954,0,2022,11,Friday,inf,0.005962
136,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0,2022,10,Sunday,inf,0.001888
137,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0,2022,11,Wednesday,inf,0.002673

In [32]:
import numpy as np

df["views_per_subscribers"] = df["views"] / df["subscribers"]
df["views_per_subscribers"] = df["views_per_subscribers"].replace([np.inf, -np.inf], 0)

In [33]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers,year,month,day_name,views_per_subscribers,engagement
0,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62,2022,9,Tuesday,461.790323,0.002986
1,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38,2022,8,Wednesday,499.394737,0.002367
2,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29,2022,9,Friday,334.517241,0.002758
3,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8,2022,9,Saturday,657.375000,0.003983
4,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17,2022,8,Friday,288.941176,0.002836
...,...,...,...,...,...,...,...,...,...,...,...
133,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0,2022,10,Monday,0.000000,0.002295
134,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0,2022,10,Sunday,0.000000,0.002763
135,YTnw6IWIlQM,Vibe With Cat of Egypt🐱🥰| #shorts #catofegypt ...,2022-11-11,16,0.0954,0,2022,11,Friday,0.000000,0.005962
136,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0,2022,10,Sunday,0.000000,0.001888
137,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0,2022,11,Wednesday,0.000000,0.002673

In [34]:
df.to_csv("cleaned_youtube_data.csv", index = False)

In [35]:
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers,year,month,day_name,views_per_subscribers,engagement
0,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62,2022,9,Tuesday,461.790323,0.002986
1,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38,2022,8,Wednesday,499.394737,0.002367
2,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29,2022,9,Friday,334.517241,0.002758
3,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8,2022,9,Saturday,657.375000,0.003983
4,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17,2022,8,Friday,288.941176,0.002836
...,...,...,...,...,...,...,...,...,...,...,...
133,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0,2022,10,Monday,0.000000,0.002295
134,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0,2022,10,Sunday,0.000000,0.002763
135,YTnw6IWIlQM,Vibe With Cat of Egypt🐱🥰| #shorts #catofegypt ...,2022-11-11,16,0.0954,0,2022,11,Friday,0.000000,0.005962
136,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0,2022,10,Sunday,0.000000,0.001888
137,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0,2022,11,Wednesday,0.000000,0.002673

In [36]:
import os
os.getcwd()

'c:\\Users\\adnan\\Downloads\\career'

In [38]:
df = pd.read_csv("cleaned_youtube_data.csv")
df

,content,video_title,video_publish_time,views,watch_time_hours,subscribers,year,month,day_name,views_per_subscribers,engagement
0,VLP3kKeNYzo,Is he a 🌄 cat or night 🦉? | #catofegypt #short...,2022-09-27,28631,85.4885,62,2022,9,Tuesday,461.790323,0.002986
1,t6BXkEw6L9I,Cat of Egypt: Carrying Your Love with me | #ca...,2022-08-17,18977,44.9220,38,2022,8,Wednesday,499.394737,0.002367
2,HYUesufltL8,"Cat of Egypt: Hello, mom you forgot to refill ...",2022-09-23,9701,26.7575,29,2022,9,Friday,334.517241,0.002758
3,veIUCvSYkos,Put an Ice cube on your pet to see their React...,2022-09-03,5259,20.9450,8,2022,9,Saturday,657.375000,0.003983
4,qkD5eaavm00,Cat of egypt: Cat starts scratching | #catofeg...,2022-08-26,4912,13.9302,17,2022,8,Friday,288.941176,0.002836
...,...,...,...,...,...,...,...,...,...,...,...
133,DAN_XXQWN0Q,When your Parents allow you to bring a caet🐱 h...,2022-10-10,21,0.0482,0,2022,10,Monday,0.000000,0.002295
134,E8AYFAu45m0,Click Here to squish a CAT 🐈 | #catofegypt #sh...,2022-10-30,19,0.0525,0,2022,10,Sunday,0.000000,0.002763
135,YTnw6IWIlQM,Vibe With Cat of Egypt🐱🥰| #shorts #catofegypt ...,2022-11-11,16,0.0954,0,2022,11,Friday,0.000000,0.005962
136,I_2paW66u2A,cat of egypt is a lil' too hangry | #shorts #c...,2022-10-02,16,0.0302,0,2022,10,Sunday,0.000000,0.001888
137,_f6xp4QNWZg,"Open the door, Surprise is waiting for you😍♥️ ...",2022-11-09,11,0.0294,0,2022,11,Wednesday,0.000000,0.002673

In [39]:
print("Hello world")

Hello world